export const IMAGES = {
    LOGO:"/images/icons/logo.svg",
    LOGOW:"/images/sideImage/Netixsol_Logo 1.svg",
    BGHERO:"/images/sideImage/herobg.png",
    HEROMAIN:"/images/sideImage/heromain.svg",
    OFFER:"/images/sideImage/offerpix.png",
    NETIXSOL:"/images/sideImage/lottieLogo.png",
    mainImg:"/images/sideImage/mainimg.svg",
    SERVICEBG:"/images/sideImage/serviceBg.png",
    NFT:"/images/sideImage/nft.svg",
    AUDIT:"/images/sideImage/audit.svg",
    CARDPIX:"/images/sideImage/cardpix2.webp",
    DEX:"/images/sideImage/dex.svg",
    DOLL:"/images/sideImage/doll.svg",
    CLOUD:"/images/icons/cloud.svg",
    ALPHA:"/images/sideImage/alphhadex.png",
    ALPHAW:"/images/sideImage/alphhadex.webp",
    AZHA:"/images/sideImage/azha.webp",
    BANNER:"/images/sideImage/banner.png",
    DEFI:"/images/sideImage/defi dino.png",
    SHARK:"/images/sideImage/shark.png",
    SW:"/images/sideImage/sw.png",
    TRUST:"/images/sideImage/TrustWallet.webp",
    ARMOR:"/images/sideImage/A.webp",
    ARBITRUM:"/images/sideImage/ArbitrumShield.webp",
    PIN:"/images/sideImage/Pin.png",
    SOLANA:"/images/sideImage/solana.png",
    BINANCE:"/images/sideImage/Binance.webp",
    HTML:"/images/sideImage/Html.webp",
    HARDHAT:"/images/sideImage/Hardhat.webp",
    VUE:"/images/sideImage/vujs.png",
    JS:"/images/sideImage/js.webp",
    AAA:"/images/sideImage/aaa.webp",
    CSS:"/images/sideImage/css.webp",
    REACT:"/images/sideImage/react.webp",
    ANGULAR:"/images/sideImage/angular.webp",
    EFH:"/images/sideImage/ethereum.png",
    UAD:"/images/sideImage/arrowupdownlogo.webp",
    TS:"/images/icons/ts.webp",
    WSS:"/images/icons/sms.webp",
    ROUND:"/images/icons/round.png",
    TELEGRAM:"/images/icons/telegram.png",
    BOX:"/images/icons/box.webp",
    BTC:"/images/icons/bitcoin.webp",
    JSS:"/images/icons/js.webp",
    MONGO:"/images/icons/mongodb.webp",
    ATOM:"/images/icons/atom.webp",
    METAMASK:"/images/icons/metamask.webp",
    POSTGREES:"/images/icons/PostgreSQL.png",
    SUSHI:"/images/icons/sushiswap-sushi-logo.png",
    REDUX:"/images/icons/redux.png",
    TRADINGVIEW:"/images/icons/TradingView.webp",
    TORN:"/images/icons/Tron.webp",
    UNISWAP:"/images/icons/uniswapwebp.webp",
    PERSONICON:"/images/icons/man-person-icon.webp",
    FLOGO:"/images/icons/footer log.webp",
    FBG:"/images/sideImage/footerbg.jpg",
    SERHERO:"/images/sideImage/ser.svg",
    SERBG:"/images/sideImage/servicemainbg.webp",
    ED:"/images/sideImage/ed.svg",
    NFT1:"/images/sideImage/nft(1).svg",
    START:"/images/sideImage/start.svg",
    H:"/images/sideImage/h.webp",
    SUBSERVICE:"/images/sideImage/subservicepix5.webp",
    GAMES:"/images/sideImage/games.svg",
    SUBSERVICES7:"/images/sideImage/subservicepix7.webp",
    SP:"/images/sideImage/sp.svg",
    ED1:"/images/sideImage/ed (1).svg",
    FRAME:"/images/sideImage/Frame.svg",
    FRAME1:"/images/sideImage/Frame (1).svg",
    FRAME2:"/images/sideImage/Frame (2).svg",
    FRAME3:"/images/sideImage/Frame (3).svg",
    FRAME4:"/images/sideImage/Frame (4).svg",
    FRAME5:"/images/sideImage/Frame (5).svg",
    FRAME6:"/images/sideImage/Frame (6).svg",
    FRAME7:"/images/sideImage/Frame (7).svg",
    COVER:"/images/sideImage/cover.png",
    PORTIMG:"/images/sideImage/blockbg.webp",
    PORTBG:"/images/sideImage/bg.webp",
    PORTBLUR:"/images/sideImage/blur.webp",
    PROJECT1:"/images/sideImage/PortfolioImg.webp",
    PROJECT2:"/images/sideImage/PortfolioImg2.webp",
    PROJECT3:"/images/sideImage/PortfolioImg3.webp",
    ABOUTBG:"/images/sideImage/hero.svg",
    A:"/images/sideImage/a.svg",
    B:"/images/sideImage/b.svg",
    C:"/images/sideImage/c.svg",
    D:"/images/sideImage/d.svg",
    E:"/images/sideImage/e.svg",
    F:"/images/sideImage/f.svg",
    APPLY:"/images/icons/apply.png",
    FIRSTSEC:"/images/icons/firstsec.svg",
    SECONDSEC:"/images/icons/secondsec.svg",
    THIRDSEC:"/images/icons/thirdsec.svg",
    ARROW:"/images/icons/arrow.png",
}